spring:
  application:
    name: core-bank-service
  # 数据库连接信息配置
  datasource:
    url: jdbc:postgresql://192.168.114.129:5432/mybank
    username: wggt
    driver-class-name: org.postgresql.Driver

# 端口号
server:
  port: 8095

eureka:
  client:
    serviceUrl:
      # 因为修改了服务器默认区域，所以要在配置中指明 
      defaultZone: http://localhost:8088/eureka