spring:
  application:
    name: bank-user-service

# 端口号
server:
  port: 8091

# Keycloak 配置
keycloak:
  config:
    serverUrl: http://192.168.114.129:8080/realms/wggt_bank_keycloak/protocol/openid-connect/auth
    realm: wggt_bank_keycloak
    username: testuser
    password: 1234
    clientId: wggt_bank_apigateway
    clientSecret: bil2JCN1sPyOcL1S6LIIKheJ3HlFA56Y

eureka:
  client:
    serviceUrl:
      # 因为修改了服务器默认区域，所以要在配置中指明 
      defaultZone: http://localhost:8088/eureka