spring:
  application:
    name: bank-user-service
  # 数据库连接信息配置
  datasource:
    url: jdbc:postgresql://192.168.114.129:5432/mybank
    username: wggt
    driver-class-name: org.postgresql.Driver

# mybatis自动驼峰映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 端口号
server:
  port: 8091

# Keycloak 配置
keycloak:
  config:
    serverUrl: http://192.168.114.129:8080
    realm: wggt_bank_keycloak

eureka:
  client:
    serviceUrl:
      # 因为修改了服务器默认区域，所以要在配置中指明 
      defaultZone: http://localhost:8088/eureka