spring:
  application:
    name: bank-api-gateway
  # 网关路由配置
  cloud:
    gateway:
      # 不加mvc默认使用的reactive
      mvc:
        routes:
          # 用户服务
            # id仅作为路由标识符，可以用任何字母数字构成
          - id: bank-user-service
            # uri可以使用http://localhost:8091 和 lb://bank-user-service
            # 用lb://bank-user-service可以使用Eureka Server自带的负载均衡器(load balancer)
            uri: lb://bank-user-service
            # predicates设置多个路由路径，例如http://localhost:8090/user 会被路由到 http://localhost:8091  
            predicates:
              - Path=/user/**
            # filters设置过滤路径，StripPrefix=1指去除1个前缀，例如http://localhost:8090/user/api 会被路由到 http://localhost:8091/api  
            filters:
              - StripPrefix=1
          # 转账服务
          - id: bank-fund-transfer-service
            uri: lb://bank-fund-transfer-service
            predicates:
              - Path=/fund-transfer/**
            filters:
              - StripPrefix=1
          # 银行核心服务
          - id: core-bank-service
            uri: lb://core-bank-service
            predicates:
              - Path=/core-bank/**
            filters:
              - StripPrefix=1
  # 安全认证配置
  security:
    # 使用OIDC协议，认证服务器会暴露网址用于认证授权用户
    oauth2:
      resourceserver:
        jwt:
          # 查看所暴露的网址格式http://{ip}:{port}/realms/{realm-name}/.well-known/openid-configuration，使用宿主机暴露的ip和端口号，realm-name使用自己创建的
          # http://192.168.114.129:8080/realms/wggt_bank_keycloak/.well-known/openid-configuration
          # issuer-uri 提供的地址必须保证 {issuer-uri}/.well-known/openid-configuration 或其它官网形式是可访问的
          issuer-uri: http://192.168.114.129:8080/realms/wggt_bank_keycloak

# 端口号
server:
  port: 8090

eureka:
  client:
    serviceUrl:
      # 因为修改了服务器默认区域，所以要在配置中指明 
      defaultZone: http://localhost:8088/eureka