spring:
  application:
    name: bank-fund-transfer-service

# 端口号
server:
  port: 8092

eureka:
  client:
    serviceUrl:
      # 因为修改了服务器默认区域，所以要在配置中指明 
      defaultZone: http://localhost:8088/eureka